### ISSUE TITLE
Program needs icon

### ISSUE THREAD

**Issue by miketvo** [miketvo/imdupes-prototype#12]
![image](https://github.com/miketvo/imdupes-prototype/assets/73817896/1f2ddd57-fa43-4ffc-b548-ae9fb6e689fa)

- Has to be extremely simple (in both shapes and colors) while still conveying the main idea
- The idea is to take a common pictograph conveying the action of copy (or duplication) - pictured above, and change the `+` sign to `⨯` sign
- Incorporate the keywords of "image" and "deduplication"

Format: `.png` (with transparency), 512x512 px

**Comment by yoantran** [comment]
icon preview: done and pr
