### ISSUE TITLE
Feature Request to display hash size information

### ISSUE THREAD

**Issue by yoantran** [miketvo/imdupes-prototype#29]
Version: 0.2.0

- Request on making a new mode in which the output only displays the calculated hash size, no scanning nor cleaning.
- Please specify the unit of the hash size.

Input:
`imdupes hash-size path/to/img/folder`

Output
`Calculated hash size: 123px`

**Comment by miketvo** [comment]
Thank you @yoantran, I am working on this feature and it should be available in the next release.
