### ISSUE TITLE
v0.2.0 Bug Report: Can't Skip Deleted Files

### ISSUE THREAD

**Issue by yoantran** [miketvo/imdupes-prototype#30]
- Tested the Clean function on program v.0.2.0 with an existed .imdup file.

`imdupes clean 'C:/Users/DELL/dupl_2.0_out_2.imdup' -V2`
**returns:**
![image](https://github.com/miketvo/imdupes-prototype/assets/92938451/9bd5e08f-ee72-4637-afb0-284823d50778)

Tthe program previously returned "access deny", and could only cleaned a few photos, which should be from my end:
![image](https://github.com/miketvo/imdupes-prototype/assets/92938451/b14340a3-b570-4e94-b990-cfa3dde11976)

After that I restarted the laptop and re-run that command, then it encountered the mentioned problem.

**Comment by miketvo** [comment]
Thank you ❤️
